pylint:
  image: python:3.7-slim
  before_script:
    - which python
    - which pip
    - pip install -r requirements-remote.txt
    - pip install pylint
    - which pylint
  script:
    - bash .pylint.sh
